import { Injectable } from '@nestjs/common';
import { 
  UserRole, 
  UserStatus, 
  PropertyStatus, 
  CollectionPointStatus, 
  BinType, 
  BinStatus, 
  BinCondition,
  DayOfWeek,
  ScheduleStatus,
  ExceptionType,
  TelemetrySource,
  TelemetryStatus,
  BinAlertType,
  AlertSeverity,
  AlertStatus,
  IoTDeviceStatus,
  WorkerEmploymentStatus,
  TeamStatus,
  TeamMemberRole,
  ShiftStatus,
  WorkerShiftStatus,
  ServiceZoneStatus,
  TeamServiceAssignmentStatus,
  AssignmentStatus,
  AssignmentPriority,
  GenerationSource,
  TargetStatus,
  AddedReason,
  CollectionEventType,
  CollectionVerification,
  WasteLoadStatus,
  FacilityType,
  FacilityStatus,
  TransferStatus,
  WeighingMethod,
  ReceiptStatus,
  ProcessType,
  MassBalanceStatus,
  CustodyEventType,
  ServiceRequestPriority,
  ServiceRequestStatus,
  ServiceRequestSource,
  CommentVisibility,
  VehicleStatus,
  VehicleType
} from '@prisma/client';

@Injectable()
export class MetaService {
  getAllEnums() {
    return {
      UserRole: Object.values(UserRole),
      UserStatus: Object.values(UserStatus),
      PropertyStatus: Object.values(PropertyStatus),
      CollectionPointStatus: Object.values(CollectionPointStatus),
      BinType: Object.values(BinType),
      BinStatus: Object.values(BinStatus),
      BinCondition: Object.values(BinCondition),
      DayOfWeek: Object.values(DayOfWeek),
      ScheduleStatus: Object.values(ScheduleStatus),
      ExceptionType: Object.values(ExceptionType),
      TelemetrySource: Object.values(TelemetrySource),
      TelemetryStatus: Object.values(TelemetryStatus),
      BinAlertType: Object.values(BinAlertType),
      AlertSeverity: Object.values(AlertSeverity),
      AlertStatus: Object.values(AlertStatus),
      IoTDeviceStatus: Object.values(IoTDeviceStatus),
      WorkerEmploymentStatus: Object.values(WorkerEmploymentStatus),
      TeamStatus: Object.values(TeamStatus),
      TeamMemberRole: Object.values(TeamMemberRole),
      ShiftStatus: Object.values(ShiftStatus),
      WorkerShiftStatus: Object.values(WorkerShiftStatus),
      ServiceZoneStatus: Object.values(ServiceZoneStatus),
      TeamServiceAssignmentStatus: Object.values(TeamServiceAssignmentStatus),
      AssignmentStatus: Object.values(AssignmentStatus),
      AssignmentPriority: Object.values(AssignmentPriority),
      GenerationSource: Object.values(GenerationSource),
      TargetStatus: Object.values(TargetStatus),
      AddedReason: Object.values(AddedReason),
      CollectionEventType: Object.values(CollectionEventType),
      CollectionVerification: Object.values(CollectionVerification),
      WasteLoadStatus: Object.values(WasteLoadStatus),
      FacilityType: Object.values(FacilityType),
      FacilityStatus: Object.values(FacilityStatus),
      TransferStatus: Object.values(TransferStatus),
      WeighingMethod: Object.values(WeighingMethod),
      ReceiptStatus: Object.values(ReceiptStatus),
      ProcessType: Object.values(ProcessType),
      MassBalanceStatus: Object.values(MassBalanceStatus),
      CustodyEventType: Object.values(CustodyEventType),
      ServiceRequestPriority: Object.values(ServiceRequestPriority),
      ServiceRequestStatus: Object.values(ServiceRequestStatus),
      ServiceRequestSource: Object.values(ServiceRequestSource),
      CommentVisibility: Object.values(CommentVisibility),
      VehicleStatus: Object.values(VehicleStatus),
      VehicleType: Object.values(VehicleType)
    };
  }
}
